name: Deploy to Azure Functions

on:
    push:
        branches:
            - itemAPI

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v3

            - name: Setup Node.js version
              uses: actions/setup-node@v4
              with:
                node-version: '18.x'

            - name: Install Dependencies
              run: npm install

            # - name: Deploy
            #   id: azure_login
            #   uses: azure/webapps-deploy@v2
            #   with:
                
            #     creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Azure Functions
              uses: azure/webapps-deploy@v2
              with:
                app-name: jsitemapi
                publish-profile : ${{secrets.AZURE_SECRET_WEBAPP_PUBLISH_PROFIL}}
                package: '.'
              # env:
              #   AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
