name: Deploy to Azure Functions

on:
  push:
    branches:
      - itemAPI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Log in to Azure
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print Azure Credentials (Debugging Step)
        run: echo "${{ secrets.AZURE_CREDENTIALS }}"
        shell: bash

      - name: Deploy Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: jsitemapi
          package: '.'
